### PR TITLE
Draft: Rzehumat/ptf

### PR DESCRIPTION
**Pull request by rzehumat**
Hi @manjavacas , sorry that it took so long. 

I attach a few initial ideas
- class `Ptf` to work with PTF files
- function `compare_ptf` -- just plotting list of PTF files comparing some variable
- (optional) I've formatted some lines according to `pep8` (feel free to reject this, it's just a personal preference...)

Just a draft so far -- some of my TODO's
- [ ] rewrite `MCRBin` into more functions -- 1 for just getting list of available variables, 1 for actually extracting the data
- [x] better error messages
- [x] passing kwargs to plots (e.g. logscale, xlim, ylim,...

### CODE REVIEW

**Comment by manjavacas** [comment]
Hi again, @rzehumat, and thank you for the contribution! 

Feel free to add any functionality you find useful to MELKIT. I will be ready to review your changes once the pull request is made.

`pep8` formatting was also one of my TO-DOs, so thanks for that 😃 

If possible, don't forget to add some usage examples to the **documentation** (chapter `Examples`). Let me know if you have any problem with this task.

Best regards

**Comment by rzehumat** [comment]
Hmm, now I'm wondering how to resolve the conflict...

**Comment by rzehumat** [comment]
EDIT: Looks like I forgot to fetch changes from the main branch to my fork. Could I ask for help here, please?

**Comment by rzehumat** [comment]
>  rewrite MCRBin into more functions -- 1 for just getting list of available variables, 1 for actually extracting the data

Let's move this into separate issue #14

**Review by manjavacas — APPROVED** [review]
Changes approved! Great job.

**Pull request merged**
